name: OpenOSRS - nightly

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Download java
        run: wget -O jdk-8u221-linux-x64.tar.gz -c --content-disposition "https://javadl.oracle.com/webapps/download/AutoDL?BundleId=239835_230deb18db3e4014bb8e3e8324f81b43"
      - name: Set up JDK 8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
          architecture: x64
          jdkFile: ./jdk-8u221-linux-x64.tar.gz

      - uses: actions/checkout@v1
        with:
          repository: open-osrs/hosting
          ref: master

      - uses: actions/checkout@v1
        with:
          repository: open-osrs/runelite
          ref: master

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/hosting/runelite
      - name: Assembling
        run: ./gradlew assemble --console=plain
        working-directory: /home/runner/work/hosting/runelite
      - name: Building
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/hosting/runelite
      - name: Bootstrap
        run: ./gradlew :runelite-client:bootstrapNightly --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/hosting/runelite

      - name: Copy bootstrap
        run: cp -af /home/runner/work/hosting/runelite/runelite-client/build/bootstrap/. /home/runner/work/hosting/hosting/

      - name: Commit changes
        uses: EndBug/add-and-commit@v2.1.0
        with:
          author_name: OpenOSRS
          author_email: openosrs.github@gmail.com
          message: "Nightly update"
          path: "."
          pattern: "*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}