name: OpenOSRS - Webhook

on: repository_dispatch

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Triggered message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#ffb347"
          username: OpenOSRS
          message: A manual ${{ github.event.action }} bootstrap has been triggered

      - name: Download java
        run: wget -O jdk-8u221-linux-x64.tar.gz -c --content-disposition "https://javadl.oracle.com/webapps/download/AutoDL?BundleId=239835_230deb18db3e4014bb8e3e8324f81b43"

      - name: Set up JDK 8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
          architecture: x64
          jdkFile: ./jdk-8u221-linux-x64.tar.gz

      - uses: actions/checkout@v1
        with:
          repository: open-osrs/hosting
          ref: master

      - uses: actions/checkout@v1
        with:
          repository: open-osrs/runelite
          ref: master

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/hosting/runelite

      - name: Assembling
        run: ./gradlew assemble --console=plain -PreleaseBuild
        working-directory: /home/runner/work/hosting/runelite

      - name: Building
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain -PreleaseBuild
        working-directory: /home/runner/work/hosting/runelite

      - name: Bootstrap nightly
        if: github.event.action == 'nightly'
        run: ./gradlew :runelite-client:bootstrapNightly --stacktrace -x test -x checkstyleMain --console=plain -PreleaseBuild
        working-directory: /home/runner/work/hosting/runelite

      - name: Bootstrap stable
        if: github.event.action == 'stable'
        run: ./gradlew :runelite-client:bootstrapStable --stacktrace -x test -x checkstyleMain --console=plain -PreleaseBuild
        working-directory: /home/runner/work/hosting/runelite

      - name: Bootstrap staging
        if: github.event.action == 'staging'
        run: ./gradlew :runelite-client:bootstrapStaging --stacktrace -x test -x checkstyleMain --console=plain -PreleaseBuild
        working-directory: /home/runner/work/hosting/runelite

      - name: Bootstrap nightly and stable
        if: github.event.action == 'nightly stable'
        run: ./gradlew :runelite-client:bootstrapNightly --stacktrace -x test -x checkstyleMain --console=plain -PreleaseBuild && ./gradlew :runelite-client:bootstrapStable --stacktrace -x test -x checkstyleMain --console=plain -PreleaseBuild
        working-directory: /home/runner/work/hosting/runelite

      - name: Copy bootstrap
        run: cp -af /home/runner/work/hosting/runelite/runelite-client/build/bootstrap/. /home/runner/work/hosting/hosting/

      - name: Create Pull Request
        uses: Owain94/create-pull-request@master
        env:
          GITHUB_TOKEN: ${{ secrets.OpenOSRS }}
          PULL_REQUEST_BRANCH: MANUAL-UPDATE
          PULL_REQUEST_TITLE: 'bootstrap: ${{ github.event.action }} release'
          PULL_REQUEST_BODY: This is an auto-generated PR with a ${{ github.event.action }} release
          COMMIT_MESSAGE: 'bootstrap: ${{ github.event.action }} release'
          PULL_REQUEST_LABELS: "automated-pull-request"

      - name: Finished message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#77dd77"
          username: OpenOSRS
          message: Manual ${{ github.event.action }} bootstrap finished
